using UnityEngine;
using System.Collections;

public class glow_controller : MonoBehaviour {
	private GameObject wkey1;
	private colorful_keys wkey1_script;
	private GameObject wkey2;
	private colorful_keys wkey2_script;
	private GameObject wkey3;
	private colorful_keys wkey3_script;
	private GameObject wkey4;
	private colorful_keys wkey4_script;
	private GameObject wkey5;
	private colorful_keys wkey5_script;
	private GameObject wkey6;
	private colorful_keys wkey6_script;
	private GameObject wkey7;
	private colorful_keys wkey7_script;
	private GameObject wkey8;
	private colorful_keys wkey8_script;
	private GameObject wkey9;
	private colorful_keys wkey9_script;
	private GameObject wkey10;
	private colorful_keys wkey10_script;
	private GameObject wkey11;
	private colorful_keys wkey11_script;
	private GameObject wkey12;
	private colorful_keys wkey12_script;
	private GameObject wkey13;
	private colorful_keys wkey13_script;
	private GameObject wkey14;
	private colorful_keys wkey14_script;
	private GameObject wkey15;
	private colorful_keys wkey15_script;
	private GameObject wkey16;
	private colorful_keys wkey16_script;
	private GameObject wkey17;
	private colorful_keys wkey17_script;
	private GameObject wkey18;
	private colorful_keys wkey18_script;
	private GameObject wkey19;
	private colorful_keys wkey19_script;
	private GameObject wkey20;
	private colorful_keys wkey20_script;
	private GameObject wkey21;
	private colorful_keys wkey21_script;
	private GameObject wkey22;
	private colorful_keys wkey22_script;
	private GameObject wkey23;
	private colorful_keys wkey23_script;
	private GameObject wkey24;
	private colorful_keys wkey24_script;
	private GameObject wkey25;
	private colorful_keys wkey25_script;
	private GameObject wkey26;
	private colorful_keys wkey26_script;
	private GameObject wkey27;
	private colorful_keys wkey27_script;
	private GameObject wkey28;
	private colorful_keys wkey28_script;
	private GameObject wkey29;
	private colorful_keys wkey29_script;
	private GameObject wkey30;
	private colorful_keys wkey30_script;
	private GameObject wkey31;
	private colorful_keys wkey31_script;
	private GameObject wkey32;
	private colorful_keys wkey32_script;
	private GameObject wkey33;
	private colorful_keys wkey33_script;
	private GameObject wkey34;
	private colorful_keys wkey34_script;
	private GameObject wkey35;
	private colorful_keys wkey35_script;
	private GameObject wkey36;
	private colorful_keys wkey36_script;
	private GameObject wkey37;
	private colorful_keys wkey37_script;
	private GameObject wkey38;
	private colorful_keys wkey38_script;
	private GameObject wkey39;
	private colorful_keys wkey39_script;
	private GameObject wkey40;
	private colorful_keys wkey40_script;
	private GameObject wkey41;
	private colorful_keys wkey41_script;
	private GameObject wkey42;
	private colorful_keys wkey42_script;
	private GameObject wkey43;
	private colorful_keys wkey43_script;
	private GameObject wkey44;
	private colorful_keys wkey44_script;
	private GameObject wkey45;
	private colorful_keys wkey45_script;
	private GameObject wkey46;
	private colorful_keys wkey46_script;
	private GameObject wkey47;
	private colorful_keys wkey47_script;
	private GameObject wkey48;
	private colorful_keys wkey48_script;
	private GameObject wkey49;
	private colorful_keys wkey49_script;
	private GameObject wkey50;
	private colorful_keys wkey50_script;
	private GameObject wkey51;
	private colorful_keys wkey51_script;
	private GameObject wkey52;
	private colorful_keys wkey52_script;




	// Use this for initialization
	void Start () {
		wkey1 = GameObject.Find("w_key1");
		wkey1_script = wkey1.GetComponent<colorful_keys>();
		wkey2 = GameObject.Find("w_key2");
		wkey2_script = wkey2.GetComponent<colorful_keys>();
		wkey3 = GameObject.Find("w_key3");
		wkey3_script = wkey3.GetComponent<colorful_keys>();
		wkey4 = GameObject.Find("w_key4");
		wkey4_script = wkey4.GetComponent<colorful_keys>();
		wkey5 = GameObject.Find("w_key5");
		wkey5_script = wkey5.GetComponent<colorful_keys>();
		wkey6 = GameObject.Find("w_key6");
		wkey6_script = wkey6.GetComponent<colorful_keys>();
		wkey7 = GameObject.Find("w_key7");
		wkey7_script = wkey7.GetComponent<colorful_keys>();
		wkey8 = GameObject.Find("w_key8");
		wkey8_script = wkey8.GetComponent<colorful_keys>();
		wkey9 = GameObject.Find("w_key9");
		wkey9_script = wkey9.GetComponent<colorful_keys>();
		wkey10 = GameObject.Find("w_key10");
		wkey10_script = wkey10.GetComponent<colorful_keys>();
		wkey11 = GameObject.Find("w_key11");
		wkey11_script = wkey11.GetComponent<colorful_keys>();
		wkey12 = GameObject.Find("w_key12");
		wkey12_script = wkey12.GetComponent<colorful_keys>();
		wkey13 = GameObject.Find("w_key13");
		wkey13_script = wkey13.GetComponent<colorful_keys>();
		wkey14 = GameObject.Find("w_key14");
		wkey14_script = wkey14.GetComponent<colorful_keys>();
		wkey15 = GameObject.Find("w_key15");
		wkey15_script = wkey15.GetComponent<colorful_keys>();
		wkey16 = GameObject.Find("w_key16");
		wkey16_script = wkey16.GetComponent<colorful_keys>();
		wkey17 = GameObject.Find("w_key17");
		wkey17_script = wkey17.GetComponent<colorful_keys>();
		wkey18 = GameObject.Find("w_key18");
		wkey18_script = wkey18.GetComponent<colorful_keys>();
		wkey19 = GameObject.Find("w_key19");
		wkey19_script = wkey19.GetComponent<colorful_keys>();
		wkey20 = GameObject.Find("w_key20");
		wkey20_script = wkey20.GetComponent<colorful_keys>();
		wkey21 = GameObject.Find("w_key21");
		wkey21_script = wkey21.GetComponent<colorful_keys>();
		wkey22 = GameObject.Find("w_key22");
		wkey22_script = wkey22.GetComponent<colorful_keys>();
		wkey23 = GameObject.Find("w_key23");
		wkey23_script = wkey23.GetComponent<colorful_keys>();
		wkey24 = GameObject.Find("w_key24");
		wkey24_script = wkey24.GetComponent<colorful_keys>();
		wkey25 = GameObject.Find("w_key25");
		wkey25_script = wkey25.GetComponent<colorful_keys>();
		wkey26 = GameObject.Find("w_key26");
		wkey26_script = wkey26.GetComponent<colorful_keys>();
		wkey27 = GameObject.Find("w_key27");
		wkey27_script = wkey27.GetComponent<colorful_keys>();
		wkey28 = GameObject.Find("w_key28");
		wkey28_script = wkey28.GetComponent<colorful_keys>();
		wkey29 = GameObject.Find("w_key29");
		wkey29_script = wkey29.GetComponent<colorful_keys>();
		wkey30 = GameObject.Find("w_key30");
		wkey30_script = wkey30.GetComponent<colorful_keys>();
		wkey31 = GameObject.Find("w_key31");
		wkey31_script = wkey31.GetComponent<colorful_keys>();
		wkey32 = GameObject.Find("w_key32");
		wkey32_script = wkey32.GetComponent<colorful_keys>();
		wkey33 = GameObject.Find("w_key33");
		wkey33_script = wkey33.GetComponent<colorful_keys>();
		wkey34 = GameObject.Find("w_key34");
		wkey34_script = wkey34.GetComponent<colorful_keys>();
		wkey35 = GameObject.Find("w_key35");
		wkey35_script = wkey35.GetComponent<colorful_keys>();
		wkey36 = GameObject.Find("w_key36");
		wkey36_script = wkey36.GetComponent<colorful_keys>();
		wkey37 = GameObject.Find("w_key37");
		wkey37_script = wkey37.GetComponent<colorful_keys>();
		wkey38 = GameObject.Find("w_key38");
		wkey38_script = wkey38.GetComponent<colorful_keys>();
		wkey39 = GameObject.Find("w_key39");
		wkey39_script = wkey39.GetComponent<colorful_keys>();
		wkey40 = GameObject.Find("w_key40");
		wkey40_script = wkey40.GetComponent<colorful_keys>();
		wkey41 = GameObject.Find("w_key41");
		wkey41_script = wkey41.GetComponent<colorful_keys>();
		wkey42 = GameObject.Find("w_key42");
		wkey42_script = wkey42.GetComponent<colorful_keys>();
		wkey43 = GameObject.Find("w_key43");
		wkey43_script = wkey43.GetComponent<colorful_keys>();
		wkey44 = GameObject.Find("w_key44");
		wkey44_script = wkey44.GetComponent<colorful_keys>();
		wkey45 = GameObject.Find("w_key45");
		wkey45_script = wkey45.GetComponent<colorful_keys>();
		wkey46 = GameObject.Find("w_key46");
		wkey46_script = wkey46.GetComponent<colorful_keys>();
		wkey47 = GameObject.Find("w_key47");
		wkey47_script = wkey47.GetComponent<colorful_keys>();
		wkey48 = GameObject.Find("w_key48");
		wkey48_script = wkey48.GetComponent<colorful_keys>();
		wkey49 = GameObject.Find("w_key49");
		wkey49_script = wkey49.GetComponent<colorful_keys>();
		wkey50 = GameObject.Find("w_key50");
		wkey50_script = wkey50.GetComponent<colorful_keys>();
		wkey51 = GameObject.Find("w_key51");
		wkey51_script = wkey51.GetComponent<colorful_keys>();
		wkey52 = GameObject.Find("w_key52");
		wkey52_script = wkey52.GetComponent<colorful_keys>();

		//wkey1_rend.material = wkey1_script.materials[0];
	}

	/*IEnumerator do_S ()
	{
		wkey22_script.glow_flag = true;
		yield return new WaitForSeconds (10);
		wkey22_script.glow_flag = false;
	}*/

	// Update is called once per frame
	void Update () {
	//	if (Input.GetKeyDown (KeyCode.Space)) 
	//		StartCoroutine(do_S());
		
		//wkey22_script.glow_flag = false;
	}
}
